/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NouraImport } from './routes/noura'

// Create/Update Routes

const NouraRoute = NouraImport.update({
  id: '/noura',
  path: '/noura',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/noura': {
      id: '/noura'
      path: '/noura'
      fullPath: '/noura'
      preLoaderRoute: typeof NouraImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/noura': typeof NouraRoute
}

export interface FileRoutesByTo {
  '/noura': typeof NouraRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/noura': typeof NouraRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/noura'
  fileRoutesByTo: FileRoutesByTo
  to: '/noura'
  id: '__root__' | '/noura'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NouraRoute: typeof NouraRoute
}

const rootRouteChildren: RootRouteChildren = {
  NouraRoute: NouraRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/noura"
      ]
    },
    "/noura": {
      "filePath": "noura.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
