/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ScreenTwoImport } from './routes/screen-two'
import { Route as ScreenOneImport } from './routes/screen-one'

// Create/Update Routes

const ScreenTwoRoute = ScreenTwoImport.update({
  id: '/screen-two',
  path: '/screen-two',
  getParentRoute: () => rootRoute,
} as any)

const ScreenOneRoute = ScreenOneImport.update({
  id: '/screen-one',
  path: '/screen-one',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screen-one': {
      id: '/screen-one'
      path: '/screen-one'
      fullPath: '/screen-one'
      preLoaderRoute: typeof ScreenOneImport
      parentRoute: typeof rootRoute
    }
    '/screen-two': {
      id: '/screen-two'
      path: '/screen-two'
      fullPath: '/screen-two'
      preLoaderRoute: typeof ScreenTwoImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/screen-one': typeof ScreenOneRoute
  '/screen-two': typeof ScreenTwoRoute
}

export interface FileRoutesByTo {
  '/screen-one': typeof ScreenOneRoute
  '/screen-two': typeof ScreenTwoRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/screen-one': typeof ScreenOneRoute
  '/screen-two': typeof ScreenTwoRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/screen-one' | '/screen-two'
  fileRoutesByTo: FileRoutesByTo
  to: '/screen-one' | '/screen-two'
  id: '__root__' | '/screen-one' | '/screen-two'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ScreenOneRoute: typeof ScreenOneRoute
  ScreenTwoRoute: typeof ScreenTwoRoute
}

const rootRouteChildren: RootRouteChildren = {
  ScreenOneRoute: ScreenOneRoute,
  ScreenTwoRoute: ScreenTwoRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/screen-one",
        "/screen-two"
      ]
    },
    "/screen-one": {
      "filePath": "screen-one.tsx"
    },
    "/screen-two": {
      "filePath": "screen-two.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
